name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Set up JDK 24
        uses: actions/setup-java@v3.1.1
        with:
          distribution: temurin
          java-version: 24
      - name: Build
        run: ./gradlew build
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: VanillaMinimaps
          path: build/libs/vanillaminimaps*.jar
